version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-ghactions-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3h3xa8pnyc74"
s3_prefix = "aws-sam-ghactions-demo"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
